# Generated by Django 2.2.5 on 2019-10-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('open', 'Mở'), ('close', 'Đóng')], default='open', max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('mua', 'Mua'), ('ban', 'Bán')], default='ban', max_length=6),
        ),
    ]
