# Generated by Django 2.2.5 on 2019-10-30 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191026_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='post/report')),
                ('content', models.TextField()),
                ('type_report', models.CharField(choices=[('sensitive', 'Nội dung nhạy cảm'), ('scam', 'Lừa đảo'), ('duplicate', 'Trùng lặp'), ('sale', 'Hàng đã bán'), ('real', 'Thông tin không giống thực tế'), ('none', 'Khác')], default='none', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='post.Post')),
            ],
        ),
    ]
