# Generated by Django 2.2 on 2019-11-02 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_category_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
