# Generated by Django 2.2 on 2019-12-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20191120_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('open', 'Mở'), ('close', 'Đóng'), ('wait', 'Đang chờ')], default='wait', max_length=6),
        ),
    ]
