# Generated by Django 2.2 on 2019-12-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
